#!/bin/bash

	echo -e "==============================================================================="
	echo -e "=== Lazy Project Create - Development + Staging - Automation system = = = ====="
	echo -e "=============================================================================== \n"

	if [ -z "$1" ] # Is parameter #1 zero length?
	then
		echo -e "=== ERROR: Requires at least one argument. Site name has to be specified."
		exit 1
	fi

	./lazyproject-create-remote $1
	./lazyproject-create-local $1

	echo -e "=== Opening site in the default browser ... \n"

	open 'http://'$1'/'
	open 'http://'$1'/wordpress/wp-admin'

	echo -e "==============================================================================="
	echo -e "=== WordPress installation and configuration finished successfully  ==========="
	echo -e "==============================================================================="
	echo -e "=== Local installation - VHost file - $APACHE_VHOSTS_CONF_DIR$1"
	echo -e "=== Local installation - Site root - $APACHE_VHOSTS_ROOT_DIR$1"
	echo -e "=== Local installation - wp.config.php - $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php"
	echo -e "=== Local installation - Address - http://$1/"
	echo -e "=== Local installation - WP-ADMIN - http://$1/wordpress/wp-admin"
	echo -e "=============================================================================== \n"
