#!/bin/bash

if [ -z "$1" ] # Is parameter #1 zero length?
then
	echo -e " \n"
	echo -e "Error: Please specify site name. \n"
	exit 1
fi

if [ ! -d $APACHE_VHOSTS_ROOT_DIR$1 ]
then
	echo -e " \n"
	echo -e "Error: No such site!"
	exit 1
fi

db_backup_path=$APACHE_VHOSTS_ROOT_DIR$1/database_backup

echo $db_backup_path

if [ ! -d $db_backup_path ]
then
	echo -e "Creating database_backup folder"
	mkdir $APACHE_VHOSTS_ROOT_DIR$1/database_backup
fi

# Get the date so that it can be used as part of the filename created
now=`date +"%m_%d_%Y_%T"`

echo -e "Exporting DB for Site: "$1
cd $APACHE_VHOSTS_ROOT_DIR$1/wordpress
wp db export $db_backup_path/$1_$now.sql

