#!/bin/bash

	MSG_INSTALL_ABORTED="Installation aborted."

	echo -e "==============================================================================="
	echo -e "=== LazyWP Install - WordPress install for lazy developers = = = =============="
	echo -e "=============================================================================== \n"

	if [ -z "$1" ] # Is parameter #1 zero length?
	then
		echo -e "=== ERROR: Requires one argument. Site name has to be specified."
		echo -e "=== e.g: lazywp-install mysite \n"
		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
		exit 1
	fi

	site_db=$1		# Name of the MySQL wordpress database
	site_db_user=$1	# Database user account
	cwd=${PWD#*/}

	hash wp &> /dev/null
	if [ $? -eq 1 ]; then
		echo >&2 "=== ERROR: wp-cli is required. Check http://wp-cli.org for more information."
		echo -e "\n=== Just execute the following command in your terminal: \n"
		echo -e "    curl https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh | bash \n"
		echo -e "    (Make sure to read the instructions) \n"
		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
		exit 1
	fi

	UP=$(pgrep mysql | wc -l);
	if [ "$UP" -ne 1 ];
	then
		echo -e "=== ERROR: MySQL not running!\n"
		echo -e "=== This script needs MySQL running in order to install and configure"
		echo -e "=== the WordPress database. \n"
		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
		exit 1
	fi

	if [ -d $MYSQL_DATA_DIR$site_db ]
	then
		echo -e "=== ERROR: Database '$site_db' aready exists! \n"
		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
		exit 1
	fi

	lazyvhost-create $1

	echo -e "=== Installing WordPress ..."
	echo -e "=== Downloading latest WordPress and extracting files."

	cd $APACHE_VHOSTS_ROOT_DIR$1
	mkdir wordpress
	cd wordpress

	wp core download | grep 'Success' > /dev/null 2>&1
	if [ $? != 0 ]
	then
		exit 1
	fi

	cd ..
	mv $APACHE_VHOSTS_ROOT_DIR$1/wordpress/wp-content $APACHE_VHOSTS_ROOT_DIR$1/content

	# Create wp-config
	{
		echo "<?php"
		echo "define('DB_NAME', '"$site_db"');"
		echo "define('DB_USER', '"$site_db_user"');"
		echo "define('DB_PASSWORD', '"$DEFAULT_MYSQL_USER_PASS"');"
		echo "define('DB_HOST', '"$MYSQL_HOST"');"
		echo "define('DB_CHARSET', 'utf8');"
		echo "define('EMPTY_TRASH_DAYS', 30 );  // 30 days"
		echo "define('DISALLOW_FILE_MODS',true); // Disable Plugin and Theme Update and Installation"
		echo "define('WP_POST_REVISIONS', 20); // Specify the Number of Post Revisions"
		echo "define('WP_HOME', 'http://"$1"');"
		echo "define('WP_SITEURL', 'http://"$1"/wordpress');"
		echo "define('WP_CONTENT_DIR', '"$APACHE_VHOSTS_ROOT_DIR$1"/content');"
		echo "define('WP_CONTENT_URL', 'http://"$1"/content');"
		echo '$table_prefix  = "wp_";'
		echo "define('WPLANG', '');"
		echo "define('WP_DEBUG', false);"
		echo "if ( !defined('ABSPATH') )"
		echo "	define('ABSPATH', dirname(__FILE__) . '/');"
		echo "	require_once(ABSPATH . 'wp-settings.php');"
	} > $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php

	# Create additional index.php file outside the WordPress folder
	{
		echo "<?php"
		echo "define('WP_USE_THEMES', true);"
		echo "require('./wordpress/wp-blog-header.php');"
		echo "?>"
	} > $APACHE_VHOSTS_ROOT_DIR$1/index.php

	# Create DB and add privileges
	mysqladmin -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" create $site_db > /dev/null 2>&1

	{ 
		echo "use mysql;"
		echo grant all on ${site_db}.* to "$site_db_user"@'localhost' identified by "'${DEFAULT_MYSQL_USER_PASS}';"
		echo "flush privileges;"
	} > $APACHE_VHOSTS_ROOT_DIR$1/sql.$$

	mysql -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" $site_db < $APACHE_VHOSTS_ROOT_DIR$1/sql.$$ > /dev/null 2>&1

	echo -e "=== Database created successfully"

	# Remove the DB & DB User generation file
	rm $APACHE_VHOSTS_ROOT_DIR$1/sql.$$

	# Go to wordpress folder and install WordPress database and the Admin account
	cd $APACHE_VHOSTS_ROOT_DIR$1/wordpress
	wp core install --url=$APACHE_VHOSTS_ROOT_DIR$1/wordpress --title=$1 --admin_name=$DEFAULT_WORDPRESS_USER_NAME --admin_email=$DEFAULT_WORDPRESS_USER_EMAIL --admin_password=$DEFAULT_WORDPRESS_USER_PASS > /dev/null 2>&1

	echo -e "=== Custom WordPress configuration finished \n"
	
	wp scaffold _s $1
	wp theme activate $1

	echo -e "=== Custom WordPress configuration finished \n"
	
	# get back to the initial directory
	cd /${cwd}

	echo -e "=== DONE! WordPress installation & configuration - Finished! \n"

	if [ $USE_CONSULAR = 1 ]
	then
		lazyconsular-installproject $1
	fi

	echo -e "=== Opening site in the default browser ... \n"
	open 'http://'$1'/'
	open 'http://'$1'/wordpress/wp-admin'

	echo -e "==============================================================================="
	echo -e "=== WordPress installation and configuration finished successfully  ==========="
	echo -e "==============================================================================="
	echo -e "=== Local installation - VHost file - $APACHE_VHOSTS_CONF_DIR$1"
	echo -e "=== Local installation - Site root - $APACHE_VHOSTS_ROOT_DIR$1"
	echo -e "=== Local installation - wp.config.php - $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php"
	echo -e "=== Local installation - Address - http://$1/"
	echo -e "=== Local installation - WP-ADMIN - http://$1/wordpress/wp-admin"
	echo -e "=============================================================================== \n"
