#!/bin/bash

if [ -z "$1" ] # Is parameter #1 zero length?
then
	echo -e "\n Error: requires site name to be specified. \n"
else

	site_db=$1			# Name of the MySQL wordpress database
	site_db_user=$1		# Database user account

	if [ -d $MYSQL_DATA_DIR$site_db ]
	then
		echo -e "Error: Database $site_db aready exists! Wordpress installation aborted! \n"
	else
		mysql.server status | grep 'SUCCESS' > /dev/null 2>&1
		if [ $? != 0 ]
		then
			echo -e 'Error: MySQL not running'
		else

			cwd=${PWD#*/}

			create-vhost $1
			
			echo -e "Installing Drupal ...\n"

			echo -e '--- MySQL server check passed: running'
			
			# cp ${APACHE_VHOSTS_ROOT_DIR}latest.tar.gz $APACHE_VHOSTS_ROOT_DIR$1
			cd $APACHE_VHOSTS_ROOT_DIR
			rm -rf $1
			drush dl drupal --drupal-project-rename=$1 > /dev/null 2>&1
			echo -e "--- getting the latest Drupal and extracting files."
			
			cd $APACHE_VHOSTS_ROOT_DIR$1

			# Create DB and add privileges
			mysqladmin -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" create $site_db > /dev/null 2>&1
			{ 
				echo "use mysql;"
				echo grant all on ${site_db}.* to "$site_db_user"@'localhost' identified by "'${DEFAULT_MYSQL_USER_PASS}';"
				echo "flush privileges;"
			} > $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
			mysql -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" $site_db < $APACHE_VHOSTS_ROOT_DIR$1/sql.$$ > /dev/null 2>&1
			echo -e "--- database & user created."
			
			# remove the database & user generation file
			rm $APACHE_VHOSTS_ROOT_DIR$1/sql.$$

			drush si standard --db-url=mysql://$site_db_user:$DEFAULT_MYSQL_USER_PASS@$MYSQL_HOST/${site_db} --account-name=$DEFAULT_DRUPAL_USER_NAME --account-pass=$DEFAULT_DRUPAL_USER_PASS --account-mail=$DEFAULT_DRUPAL_USER_EMAIL --site-name=$1

			echo -e "Drupal installation & configuration - Finished! \n"

			open 'http://'$1'/'

			# get back to the initial directory
			cd /${cwd}
		fi
	fi
fi
